<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>Developer Island</Company>
    <Product>Developer Island</Product>
    <Version>0.1.0</Version>
    <Copyright>Copyright © 2026 Maximilian Köhlenbeck</Copyright>
  </PropertyGroup>
</Project>
